<script setup lang="ts">
import {computed,ref} from 'vue';import {useRouter} from 'vue-router';import PageHeader from '../../components/common/PageHeader.vue';import SegmentTabs from '../../components/common/SegmentTabs.vue';import EmptyState from '../../components/common/EmptyState.vue';import StatusTag from '../../components/common/StatusTag.vue';import {workbenchRepository} from '../../services/workbenchRepository';
const router=useRouter();const data=ref(workbenchRepository.load());const taskTab=ref('pending');const approvalTab=ref('pending');const feedTab=ref('dynamic');
const tasks=computed(()=>data.value.tasks.filter(item=>taskTab.value==='done'?item.status==='已完成':item.status!=='已完成'));
const approvals=computed(()=>data.value.approvals.filter(item=>approvalTab.value==='history'?item.status!=='待审批':item.status==='待审批'));
const feeds={dynamic:[['10分钟前','师创智联OS V3.5.2 已发布至预发环境'],['1小时前','研发任务筛选能力进入验收']],feedback:[['今天 09:30','客户反馈移动端弱网体验明显改善'],['昨天 17:40','4K宽屏仍有局部适配问题']],supervise:[['今天 09:20','国家电网合同审批需今日完成'],['昨天 16:10','述标材料等待技术负责人确认']]};
const go=(id:string)=>router.push(`/app/${id}`);
</script>
<template><section class="workbench-view"><PageHeader eyebrow="WORKBENCH" title="我的工作台" description="聚合待办、审批、目标和近期业务动态。"><template #actions><button class="secondary" @click="go('wb_work_orders')">进入工单中心</button></template></PageHeader><div class="metric-grid compact"><article @click="go('prod_req_tasks')"><span>待办事项</span><strong>{{data.tasks.filter(x=>x.status!=='已完成').length}}</strong><small>项</small></article><article @click="go('approval_center')"><span>待办审批</span><strong>{{data.approvals.filter(x=>x.status==='待审批').length}}</strong><small>单</small></article><article @click="go('wb_okr_perf')"><span>目标平均进度</span><strong>{{Math.round(data.okrs.reduce((n,x)=>n+x.progress,0)/data.okrs.length)}}%</strong><small>本月</small></article><article @click="go('wb_knowledge')"><span>知识文档</span><strong>{{data.documents.length}}</strong><small>篇</small></article></div><div class="dashboard-grid"><article class="panel"><div class="panel-head"><h3>待办中心</h3><button class="link-button" @click="go('prod_req_tasks')">查看全部</button></div><SegmentTabs v-model="taskTab" :items="[{key:'pending',label:'待处理',count:data.tasks.filter(x=>x.status!=='已完成').length},{key:'done',label:'已完成',count:data.tasks.filter(x=>x.status==='已完成').length}]"/><div v-if="tasks.length" class="stack-list"><button v-for="item in tasks" :key="item.id" class="list-row" @click="go('prod_req_tasks')"><span><strong>{{item.title}}</strong><small>{{item.productLine}} · 截止 {{item.dueDate}}</small></span><StatusTag :status="item.priority"/></button></div><EmptyState v-else title="暂无任务"/></article><article class="panel"><div class="panel-head"><h3>审批流程</h3><button class="link-button" @click="go('approval_center')">查看全部</button></div><SegmentTabs v-model="approvalTab" :items="[{key:'pending',label:'待审批'},{key:'history',label:'已审批'}]"/><div v-if="approvals.length" class="stack-list"><button v-for="item in approvals" :key="item.id" class="list-row" @click="go('approval_center')"><span><strong>{{item.title}}</strong><small>{{item.applicant}} · {{item.createdAt}}</small></span><StatusTag :status="item.status"/></button></div><EmptyState v-else title="暂无审批"/></article><article class="panel"><div class="panel-head"><h3>我的 OKR</h3><button class="link-button" @click="go('wb_okr_perf')">目标详情</button></div><div v-for="okr in data.okrs.filter(x=>x.category==='my')" :key="okr.id" class="okr-summary"><strong>{{okr.objective}}</strong><span>{{okr.progress}}%</span><div class="progress"><i :style="{width:`${okr.progress}%`}"/></div><small>截止 {{okr.deadline}}</small></div></article><article class="panel"><div class="panel-head"><h3>动态与评价</h3></div><SegmentTabs v-model="feedTab" :items="[{key:'dynamic',label:'产品动态'},{key:'feedback',label:'评价反馈'},{key:'supervise',label:'督办事项'}]"/><div class="timeline"><div v-for="item in feeds[feedTab as keyof typeof feeds]" :key="item[1]"><time>{{item[0]}}</time><p>{{item[1]}}</p></div></div></article></div></section></template>
