-- 为独立任务表补齐来源需求关联，使用信息_schema 判断以兼容已升级数据库。
SET @schema_name = DATABASE();
SET @sql = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=@schema_name AND table_name='t_crm_presales_task' AND column_name='requirement_id_')=0, 'ALTER TABLE t_crm_presales_task ADD COLUMN requirement_id_ VARCHAR(36) NULL', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=@schema_name AND table_name='t_project_delivery_task' AND column_name='requirement_id_')=0, 'ALTER TABLE t_project_delivery_task ADD COLUMN requirement_id_ VARCHAR(36) NULL', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=@schema_name AND table_name='t_project_ops_task' AND column_name='requirement_id_')=0, 'ALTER TABLE t_project_ops_task ADD COLUMN requirement_id_ VARCHAR(36) NULL', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=@schema_name AND table_name='t_product_design_task' AND column_name='requirement_id_')=0, 'ALTER TABLE t_product_design_task ADD COLUMN requirement_id_ VARCHAR(36) NULL', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF((SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema=@schema_name AND table_name='t_crm_presales_task' AND index_name='idx_presales_task_requirement')=0, 'CREATE INDEX idx_presales_task_requirement ON t_crm_presales_task (tenant_id_, requirement_id_, status_, create_time_)', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF((SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema=@schema_name AND table_name='t_project_delivery_task' AND index_name='idx_delivery_task_requirement')=0, 'CREATE INDEX idx_delivery_task_requirement ON t_project_delivery_task (tenant_id_, requirement_id_, status_, create_time_)', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF((SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema=@schema_name AND table_name='t_project_ops_task' AND index_name='idx_ops_task_requirement')=0, 'CREATE INDEX idx_ops_task_requirement ON t_project_ops_task (tenant_id_, requirement_id_, status_, create_time_)', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF((SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema=@schema_name AND table_name='t_product_design_task' AND index_name='idx_design_task_requirement')=0, 'CREATE INDEX idx_design_task_requirement ON t_product_design_task (tenant_id_, requirement_id_, status_, create_time_)', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
