-- 七类任务统一补充租户、状态、来源需求查询索引，重复执行安全。
SET @schema_name = DATABASE();
SET @sql = IF((SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema=@schema_name AND table_name='t_product_requirement_task' AND index_name='idx_requirement_task_tenant_status')=0, 'CREATE INDEX idx_requirement_task_tenant_status ON t_product_requirement_task (tenant_id_, status_, create_time_)', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF((SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema=@schema_name AND table_name='t_product_design_task' AND index_name='idx_design_task_tenant_status')=0, 'CREATE INDEX idx_design_task_tenant_status ON t_product_design_task (tenant_id_, status_, create_time_)', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF((SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema=@schema_name AND table_name='t_crm_presales_task' AND index_name='idx_presales_task_tenant_status')=0, 'CREATE INDEX idx_presales_task_tenant_status ON t_crm_presales_task (tenant_id_, status_, create_time_)', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF((SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema=@schema_name AND table_name='t_project_delivery_task' AND index_name='idx_delivery_task_tenant_status')=0, 'CREATE INDEX idx_delivery_task_tenant_status ON t_project_delivery_task (tenant_id_, status_, create_time_)', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF((SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema=@schema_name AND table_name='t_project_ops_task' AND index_name='idx_ops_task_tenant_status')=0, 'CREATE INDEX idx_ops_task_tenant_status ON t_project_ops_task (tenant_id_, status_, create_time_)', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF((SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema=@schema_name AND table_name='t_product_requirement_task' AND index_name='idx_requirement_task_source')=0, 'CREATE INDEX idx_requirement_task_source ON t_product_requirement_task (tenant_id_, requirement_id_, delete_flag_)', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF((SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema=@schema_name AND table_name='t_product_design_task' AND index_name='idx_design_task_source')=0, 'CREATE INDEX idx_design_task_source ON t_product_design_task (tenant_id_, requirement_id_, delete_flag_)', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF((SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema=@schema_name AND table_name='t_crm_presales_task' AND index_name='idx_presales_task_source')=0, 'CREATE INDEX idx_presales_task_source ON t_crm_presales_task (tenant_id_, requirement_id_, delete_flag_)', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF((SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema=@schema_name AND table_name='t_project_delivery_task' AND index_name='idx_delivery_task_source')=0, 'CREATE INDEX idx_delivery_task_source ON t_project_delivery_task (tenant_id_, requirement_id_, delete_flag_)', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF((SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema=@schema_name AND table_name='t_project_ops_task' AND index_name='idx_ops_task_source')=0, 'CREATE INDEX idx_ops_task_source ON t_project_ops_task (tenant_id_, requirement_id_, delete_flag_)', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
