-- Additive storage only: existing business records and workflow history are not rewritten.
CREATE TABLE t_product_workflow (
  id_ VARCHAR(36) PRIMARY KEY,
  tenant_id_ VARCHAR(36) NOT NULL,
  product_line_id_ VARCHAR(36) NOT NULL,
  category_ VARCHAR(16) NOT NULL,
  workflow_version_ INT NOT NULL,
  name_ VARCHAR(128) NOT NULL,
  status_ VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
  definition_ JSON NOT NULL,
  version_ INT NOT NULL DEFAULT 0,
  create_by_ VARCHAR(36) NOT NULL,
  update_by_ VARCHAR(36) NOT NULL,
  create_time_ DATETIME(6) NOT NULL,
  update_time_ DATETIME(6) NOT NULL,
  delete_flag_ TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_workflow_version (tenant_id_,product_line_id_,category_,workflow_version_),
  KEY idx_workflow_published (tenant_id_,product_line_id_,category_,status_,delete_flag_)
);

CREATE TABLE t_product_work_item (
  id_ VARCHAR(36) PRIMARY KEY,
  tenant_id_ VARCHAR(36) NOT NULL,
  product_line_id_ VARCHAR(36) NOT NULL,
  category_ VARCHAR(16) NOT NULL,
  task_type_id_ VARCHAR(36) NOT NULL,
  code_ VARCHAR(64) NOT NULL,
  title_ VARCHAR(255) NOT NULL,
  description_ LONGTEXT,
  expected_goal_ TEXT,
  version_id_ VARCHAR(36),
  requirement_id_ VARCHAR(36),
  parent_work_item_id_ VARCHAR(36),
  workflow_id_ VARCHAR(36) NOT NULL,
  status_key_ VARCHAR(64) NOT NULL,
  status_name_ VARCHAR(128) NOT NULL,
  status_group_ VARCHAR(16) NOT NULL,
  successful_ TINYINT NOT NULL DEFAULT 0,
  assignee_id_ VARCHAR(36),
  assignee_name_ VARCHAR(128),
  priority_ VARCHAR(2) NOT NULL,
  planned_start_date_ DATE,
  planned_end_date_ DATE,
  actual_start_at_ DATETIME(6),
  completed_at_ DATETIME(6),
  estimated_hours_ DECIMAL(10,2) NOT NULL DEFAULT 0,
  actual_hours_ DECIMAL(10,2) NOT NULL DEFAULT 0,
  source_type_ VARCHAR(32) NOT NULL DEFAULT 'MANUAL',
  request_id_ VARCHAR(64) NOT NULL,
  request_hash_ VARCHAR(64) NOT NULL,
  version_ INT NOT NULL DEFAULT 0,
  create_by_ VARCHAR(36) NOT NULL,
  update_by_ VARCHAR(36) NOT NULL,
  create_time_ DATETIME(6) NOT NULL,
  update_time_ DATETIME(6) NOT NULL,
  delete_flag_ TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_work_item_request (tenant_id_,product_line_id_,request_id_),
  UNIQUE KEY uk_work_item_code (tenant_id_,code_),
  KEY idx_work_item_line (tenant_id_,product_line_id_,category_,delete_flag_,create_time_),
  KEY idx_work_item_version (tenant_id_,version_id_,delete_flag_,status_group_),
  KEY idx_work_item_parent (tenant_id_,parent_work_item_id_,delete_flag_),
  KEY idx_work_item_requirement (tenant_id_,requirement_id_,delete_flag_),
  KEY idx_work_item_type (tenant_id_,task_type_id_,delete_flag_)
);

CREATE TABLE t_product_work_item_child_rule (
  id_ VARCHAR(36) PRIMARY KEY,
  tenant_id_ VARCHAR(36) NOT NULL,
  product_line_id_ VARCHAR(36) NOT NULL,
  parent_type_id_ VARCHAR(36) NOT NULL,
  child_type_id_ VARCHAR(36) NOT NULL,
  enabled_ TINYINT NOT NULL DEFAULT 1,
  version_ INT NOT NULL DEFAULT 0,
  create_by_ VARCHAR(36) NOT NULL,
  update_by_ VARCHAR(36) NOT NULL,
  create_time_ DATETIME(6) NOT NULL,
  update_time_ DATETIME(6) NOT NULL,
  delete_flag_ TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_work_item_child_rule (tenant_id_,product_line_id_,parent_type_id_,child_type_id_)
);

CREATE TABLE t_product_work_item_activity (
  id_ VARCHAR(36) PRIMARY KEY,
  tenant_id_ VARCHAR(36) NOT NULL,
  product_line_id_ VARCHAR(36) NOT NULL,
  subject_id_ VARCHAR(36) NOT NULL,
  event_type_ VARCHAR(64) NOT NULL,
  content_ JSON NOT NULL,
  create_by_ VARCHAR(36) NOT NULL,
  create_time_ DATETIME(6) NOT NULL,
  KEY idx_work_item_activity (tenant_id_,product_line_id_,subject_id_,create_time_)
);
