import { Alert, Button, DatePicker, Empty, Flex, Form, Input, InputNumber, Select, Tag, Typography } from 'antd';
import Card from 'antd/es/card/Card';
import { PlusIcon, TrashIcon, GitBranchIcon } from '@primer/octicons-react';
import dayjs from 'dayjs';
import { useState } from 'react';
import type { OkrActionPayload, OkrPerson, OkrRecord } from '../../../services/okrRepository';

const departmentType = (department: string) => /产研|产品|研发|技术/.test(department) ? 'product' : /售前|销售|市场/.test(department) ? 'presales' : /交付|项目|实施/.test(department) ? 'delivery' : 'support';
type ActionValues = { recordId?: string; version?: number; title: string; businessObject?: string; milestone?: string; deadline?: dayjs.Dayjs; weight?: number; assigneeIds?: string[] };

export function ActionBreakdownForm({ open, cycle, person, parents, actions, people, busy, onClose, onSave }: { open: boolean; cycle: string; person?: OkrPerson; parents: OkrRecord[]; actions: OkrRecord[]; people: OkrPerson[]; busy: boolean; onClose: () => void; onSave: (parent: OkrRecord, values: ActionValues[], mode: 'draft'|'submit') => Promise<boolean>; }) {
  const [form] = Form.useForm(); const [activeParentId, setActiveParentId] = useState<string>(); const [collapsed, setCollapsed] = useState<Set<string>>(new Set()); const [savingMode, setSavingMode] = useState<'draft'|'submit'>('submit');
  if (!open) return null;
  const type = departmentType(person?.department || ''); const structureLabel = type === 'product' ? '关联产品线' : type === 'presales' ? '关联线索/商机' : type === 'delivery' ? '关联项目' : '验收标准'; const activeParent = parents.find(parent => parent.id === activeParentId); const childrenOf = (parentId: string) => actions.filter(action => action.payload.parentActionId === parentId);
  const openEditor = (parent: OkrRecord) => { setActiveParentId(parent.id); form.resetFields(); const drafts = actions.filter(action => action.payload.parentActionId === parent.id && action.status === 'draft'); form.setFieldsValue({actions: drafts.length ? drafts.map(action => ({recordId: action.id, version: action.version, title: action.payload.title, businessObject: action.payload.businessObject || action.payload.productLine || action.payload.acceptanceStandard, milestone: action.payload.milestone, deadline: action.payload.deadline ? dayjs(action.payload.deadline) : undefined, weight: action.payload.weight, assigneeIds: action.payload.assigneeIds || []})) : [{weight: 100, assigneeIds: []}]}); }; const closeEditor = () => { setActiveParentId(undefined); form.resetFields(); };
  const submit = async (values: {actions: ActionValues[]}) => { if (!activeParent) return; if (await onSave(activeParent, values.actions || [], savingMode)) closeEditor(); };
  const childDetail = (child: OkrRecord) => child.payload.productLine || child.payload.businessObject || child.payload.acceptanceStandard || '—';
  return <Card className="okr-action-breakdown-card"><div className="okr-action-breakdown-page" aria-label="拆解动作"><div className="okr-objective-period okr-action-period"><span className="okr-action-period-label">{dayjs(cycle).format('YYYY年MM月')}<span>进行中</span></span><Flex className="okr-action-period-actions" gap="small" align="center"><Button onClick={onClose} disabled={busy}>取消</Button><Button onClick={() => { setSavingMode('draft'); void form.submit(); }} loading={busy && savingMode === 'draft'} disabled={busy}>存草稿</Button><Button type="primary" onClick={() => { setSavingMode('submit'); void form.submit(); }} loading={busy && savingMode === 'submit'} disabled={busy}>提交</Button></Flex></div>
    {parents.length === 0 ? <Card><Empty description="暂无指定给你的承接动作" /></Card> : <Flex vertical gap="middle">{parents.map((parent, parentIndex) => { const children = childrenOf(parent.id); const isActive = activeParentId === parent.id; return <Card key={parent.id} className="okr-action-parent-tree-card"><div className="okr-action-parent-tree-head"><div className="okr-action-o-title"><span className="okr-summary-index">O{parentIndex + 1}</span><Typography.Text strong>{parent.payload.title}</Typography.Text></div><Button type="text" aria-label={isActive ? '取消拆解' : '拆解动作'} title={isActive ? '取消拆解' : '拆解动作'} icon={<GitBranchIcon size={16} />} onClick={() => isActive ? closeEditor() : openEditor(parent)} /></div>
      {isActive && activeParent && <Card size="small" className="okr-action-inline-editor" title={<Flex justify="space-between"><span>新增关键动作</span><Button type="text" icon={<PlusIcon />} onClick={() => form.setFieldsValue({actions: [...(form.getFieldValue('actions') || []), {weight: 0, assigneeIds: []}]})}>继续添加</Button></Flex>}><Alert className="mb-4" type="info" showIcon title="当前动作将自动作为上级关系，无需再次选择" /><Form form={form} layout="vertical" disabled={busy} onFinish={submit}><Form.List name="actions">{(fields, {remove}) => <Flex vertical gap="middle">{fields.map((field, index) => <Card key={field.key} size="small" title={`关键动作 ${index + 1}`} extra={<Button type="text" onClick={() => setCollapsed(current => { const next = new Set(current); const key = `${parent.id}-${field.key}`; next.has(key) ? next.delete(key) : next.add(key); return next; })}>{collapsed.has(`${parent.id}-${field.key}`) ? '展开' : '收起'}</Button>}>{!collapsed.has(`${parent.id}-${field.key}`) && <><Form.Item name={[field.name, 'title']} label="输入动作" rules={[{required: true, whitespace: true, message: '请输入动作'}]}><Input.TextArea autoSize={{minRows: 2, maxRows: 4}} maxLength={2000} /></Form.Item><Form.Item name={[field.name, 'businessObject']} label={structureLabel} rules={[{required: true, whitespace: true, message: `请输入${structureLabel}`}]}><Input maxLength={500} /></Form.Item>{type !== 'support' && <Form.Item name={[field.name, 'milestone']} label="关键节点" rules={[{required: true, whitespace: true, message: '请输入关键节点'}]}><Input maxLength={500} /></Form.Item>}<Flex gap="middle" wrap><Form.Item className="flex-1" name={[field.name, 'deadline']} label="完成时间" rules={[{required: true, message: '请选择完成时间'}]}><DatePicker className="w-full" /></Form.Item><Form.Item name={[field.name, 'weight']} label="权重" rules={[{required: true, type: 'number', min: 1, max: 100}]}><InputNumber min={1} max={100} precision={0} suffix="%" /></Form.Item></Flex><Form.Item name={[field.name, 'assigneeIds']} label="承接人员（可多选）"><Select mode="multiple" allowClear showSearch optionFilterProp="label" placeholder="可不指定" options={people.map(item => ({value: item.id, label: `${item.name} · ${item.department}`}))} /></Form.Item><Button danger type="text" icon={<TrashIcon />} disabled={fields.length <= 1} onClick={() => remove(field.name)}>删除动作</Button></>}</Card>)}</Flex>}</Form.List></Form></Card>}
      {children.length ? <div className="okr-action-child-list">{children.map((child, index) => <div key={child.id} className="okr-action-child-item"><span className="okr-action-child-index">A{index + 1}</span><Typography.Text>{child.payload.title}</Typography.Text><Typography.Text type="secondary">{child.payload.department}</Typography.Text><Typography.Text type="secondary">{child.payload.assigneeName || '未指定承接人员'}</Typography.Text><Typography.Text type="secondary">{child.payload.deadline}</Typography.Text>{child.status === 'draft' && <Button type="link" onClick={() => openEditor(parent)}>编辑草稿</Button>}<Button type="link" onClick={() => setCollapsed(current => { const next = new Set(current); next.has(child.id) ? next.delete(child.id) : next.add(child.id); return next; })}>{collapsed.has(child.id) ? '展开详情' : '收起详情'}</Button>{!collapsed.has(child.id) && <div className="okr-action-child-detail"><span>{childDetail(child)}</span><span>{child.payload.milestone || '—'}</span><span>权重 {child.payload.weight || 0}%</span></div>}</div>)}</div> : <Typography.Paragraph type="secondary" className="okr-action-empty-child">暂无子动作，点击右侧图标开始拆解</Typography.Paragraph>}</Card>; })}</Flex>}
  </div></Card>;
}
