import { Button, DatePicker, Empty, Flex, Form, Input, InputNumber, Select, Tag, Typography } from 'antd';
import Card from 'antd/es/card/Card';
import { PlusIcon, TrashIcon, GitBranchIcon } from '@primer/octicons-react';
import dayjs from 'dayjs';
import { useEffect, useState, type Key } from 'react';
import type { OkrPerson, OkrRecord } from '../../../services/okrRepository';

const departmentType = (department: string) => /产研|产品|研发|技术/.test(department) ? 'product' : /售前|销售|市场/.test(department) ? 'presales' : /交付|项目|实施/.test(department) ? 'delivery' : 'support';
type ActionValues = { recordId?: string; version?: number; title: string; businessObject?: string; milestone?: string; deadline?: dayjs.Dayjs; weight?: number; assigneeIds?: string[] };

export function ActionBreakdownForm({ open, cycle, person, parents, actions, people, busy, onClose, onSave, initialActionId }: { key?: Key; open: boolean; cycle: string; person?: OkrPerson; parents: OkrRecord[]; actions: OkrRecord[]; people: OkrPerson[]; busy: boolean; onClose: () => void; onSave: (parent: OkrRecord, values: ActionValues[], mode: 'draft'|'submit') => Promise<boolean>; initialActionId?: string; }) {
  const [form] = Form.useForm(); const [activeParentId, setActiveParentId] = useState<string>(); const [collapsedParents, setCollapsedParents] = useState<Set<string>>(new Set()); const [savingMode, setSavingMode] = useState<'draft'|'submit'>('submit');
  const type = departmentType(person?.department || ''); const structureLabel = type === 'product' ? '关联产品线' : type === 'presales' ? '关联线索/商机' : type === 'delivery' ? '关联项目' : '验收标准'; const activeParent = parents.find(parent => parent.id === activeParentId); const childrenOf = (parent: OkrRecord) => actions.filter(action => action.payload.parentActionId === (parent.payload.parentActionId || parent.id) && action.payload.parentObjectiveId === parent.payload.parentObjectiveId && (action.payload.parentKeyResultId || action.payload.parentActionId) === (parent.payload.parentKeyResultId || parent.id) && action.status !== 'draft');
  const openEditor = (parent: OkrRecord, actionId?: string) => { setActiveParentId(parent.id); form.resetFields(); const drafts = actionId ? actions.filter(action => action.id === actionId && action.status === 'draft') : []; form.setFieldsValue({actions: drafts.length ? drafts.map(action => ({recordId: action.id, version: action.version, title: action.payload.title, businessObject: action.payload.businessObject || action.payload.productLine || action.payload.acceptanceStandard, milestone: action.payload.milestone, deadline: action.payload.deadline ? dayjs(action.payload.deadline) : undefined, weight: action.payload.weight, assigneeIds: action.payload.assigneeIds || []})) : [{weight: undefined, assigneeIds: []}]}); }; const closeEditor = () => { setActiveParentId(undefined); form.resetFields(); };
  useEffect(() => {
    if (!open || !initialActionId) return;
    const action = actions.find(item => item.id === initialActionId);
    const parent = action ? parents.find(item => item.id === action.payload.parentActionId && item.payload.parentObjectiveId === action.payload.parentObjectiveId) : undefined;
    if (parent) openEditor(parent, initialActionId);
  }, [open, initialActionId, actions, parents]);
  if (!open) return null;
  const submit = async (values: {actions: ActionValues[]}, mode = savingMode) => { if (!activeParent) return; if (await onSave(activeParent, values.actions || [], mode)) closeEditor(); };
  const submitWithMode = (mode: 'draft' | 'submit') => {
    if (!activeParent) return;
    setSavingMode(mode);
    void form.validateFields().then(values => submit(values, mode)).catch(() => undefined);
  };
  const submitDraftEditor = async () => {
    if (!activeParent) return;
    try { const values = await form.validateFields(); await submit(values, savingMode); } catch { /* Keep the draft open for correction. */ }
  };
  const childDetail = (child: OkrRecord) => child.payload.productLine || child.payload.businessObject || child.payload.acceptanceStandard || '—';
  if (initialActionId && activeParent) {
    return <Card className="okr-action-breakdown-card"><div className="okr-action-breakdown-page" aria-label="拆解动作草稿编辑"><div className="okr-objective-period okr-action-period"><span className="okr-action-period-label">{dayjs(cycle).format('YYYY年MM月')}<span>草稿</span></span><Flex className="okr-action-period-actions" gap="small" align="center"><Button onClick={onClose} disabled={busy}>取消</Button><Button onClick={async () => { setSavingMode('draft'); await submitDraftEditor(); }} loading={busy && savingMode === 'draft'} disabled={busy}>存草稿</Button><Button type="primary" onClick={async () => { setSavingMode('submit'); await submitDraftEditor(); }} loading={busy && savingMode === 'submit'} disabled={busy}>提交</Button></Flex></div>{activeParent && <Card className="okr-action-parent-tree-card"><div className="okr-action-parent-tree-head"><div className="okr-action-o-title"><span className="okr-summary-index">O</span><Typography.Text strong>{activeParent.payload.title}</Typography.Text></div></div><Form form={form} layout="vertical" disabled={busy}><Form.List name="actions">{fields => <Flex vertical gap="middle">{fields.map((field, index) => <section key={field.key} className="okr-action-edit-section"><Typography.Text strong>关键动作 {index + 1}</Typography.Text><Form.Item name={[field.name, 'title']} label="输入动作" rules={[{required: true, whitespace: true, message: '请输入动作'}]}><Input.TextArea autoSize={{minRows: 2, maxRows: 4}} maxLength={2000} /></Form.Item><Form.Item name={[field.name, 'businessObject']} label={structureLabel} rules={[{required: true, whitespace: true, message: `请输入${structureLabel}`}]}><Input maxLength={500} /></Form.Item>{type !== 'support' && <Form.Item name={[field.name, 'milestone']} label="关键节点" rules={[{required: true, whitespace: true, message: '请输入关键节点'}]}><Input maxLength={500} /></Form.Item>}<Flex gap="middle" wrap><Form.Item className="flex-1" name={[field.name, 'deadline']} label="完成时间" rules={[{required: true, message: '请选择完成时间'}]}><DatePicker className="w-full" /></Form.Item><Form.Item name={[field.name, 'weight']} label="权重" rules={[{required: true, type: 'number', min: 1, max: 100}]}><InputNumber min={1} max={100} precision={0} suffix="%" /></Form.Item></Flex><Form.Item name={[field.name, 'assigneeIds']} label="承接人员（可多选）"><Select mode="multiple" allowClear showSearch optionFilterProp="label" placeholder="可不指定" options={people.map(item => ({value: item.id, label: `${item.name} · ${item.department}`}))} /></Form.Item></section>)}</Flex>}</Form.List></Form></Card>}</div></Card>;
  }
  return <Card className="okr-action-breakdown-card"><div className="okr-action-breakdown-page" aria-label="拆解动作"><div className="okr-objective-period okr-action-period"><span className="okr-action-period-label">{dayjs(cycle).format('YYYY年MM月')}<span>进行中</span></span><Flex className="okr-action-period-actions" gap="small" align="center"><Button onClick={onClose} disabled={busy}>取消</Button><Button onClick={() => submitWithMode('draft')} loading={busy && savingMode === 'draft'} disabled={busy}>存草稿</Button><Button type="primary" onClick={() => submitWithMode('submit')} loading={busy && savingMode === 'submit'} disabled={busy}>提交</Button></Flex></div>
    {parents.length === 0 ? <Card><Empty description="暂无指定给你的承接动作" /></Card> : <Flex vertical gap="middle">{parents.map((parent, parentIndex) => { const children = childrenOf(parent); const isActive = activeParentId === parent.id; const isCollapsed = collapsedParents.has(parent.id); return <Card key={parent.id} className="okr-action-parent-tree-card"><div className="okr-action-parent-tree-head"><div className="okr-action-o-title"><span className="okr-summary-index">O{parentIndex + 1}</span><Typography.Text strong>{parent.payload.title}</Typography.Text></div><Flex gap="small"><Button type="text" onClick={() => setCollapsedParents(current => { const next = new Set(current); next.has(parent.id) ? next.delete(parent.id) : next.add(parent.id); return next; })}>{isCollapsed ? '展开' : '收起'}</Button><Button type="text" aria-label={isActive ? '取消拆解' : '拆解动作'} title={isActive ? '取消拆解' : '拆解动作'} icon={<GitBranchIcon size={16} />} onClick={() => isActive ? closeEditor() : openEditor(parent)} /></Flex></div>
      {!isCollapsed && <>{isActive && activeParent && <Card size="small" className="okr-action-inline-editor" title={<Flex justify="space-between"><span>{initialActionId ? '编辑拆解动作草稿' : '新增关键动作'}</span><Button type="text" icon={<PlusIcon />} onClick={() => form.setFieldsValue({actions: [...(form.getFieldValue('actions') || []), {weight: undefined, assigneeIds: []}]})}>继续添加</Button></Flex>}><Form form={form} layout="vertical" disabled={busy} onFinish={submit}><Form.List name="actions">{(fields, {remove}) => <Flex vertical gap="middle">{fields.map((field, index) => <section key={field.key} className="okr-action-edit-section"><Typography.Text strong>关键动作 {index + 1}</Typography.Text><Form.Item name={[field.name, 'title']} label="输入动作" rules={[{required: true, whitespace: true, message: '请输入动作'}]}><Input.TextArea autoSize={{minRows: 2, maxRows: 4}} maxLength={2000} /></Form.Item><Form.Item name={[field.name, 'businessObject']} label={structureLabel} rules={[{required: true, whitespace: true, message: `请输入${structureLabel}`}]}><Input maxLength={500} /></Form.Item>{type !== 'support' && <Form.Item name={[field.name, 'milestone']} label="关键节点" rules={[{required: true, whitespace: true, message: '请输入关键节点'}]}><Input maxLength={500} /></Form.Item>}<Flex gap="middle" wrap><Form.Item className="flex-1" name={[field.name, 'deadline']} label="完成时间" rules={[{required: true, message: '请选择完成时间'}]}><DatePicker className="w-full" /></Form.Item><Form.Item name={[field.name, 'weight']} label="权重" rules={[{required: true, type: 'number', min: 1, max: 100}]}><InputNumber min={1} max={100} precision={0} suffix="%" /></Form.Item></Flex><Form.Item name={[field.name, 'assigneeIds']} label="承接人员（可多选）"><Select mode="multiple" allowClear showSearch optionFilterProp="label" placeholder="可不指定" options={people.map(item => ({value: item.id, label: `${item.name} · ${item.department}`}))} /></Form.Item><Button danger type="text" icon={<TrashIcon />} disabled={fields.length <= 1} onClick={() => remove(field.name)}>删除动作</Button></section>)}</Flex>}</Form.List></Form></Card>}
      {children.length ? <div className="okr-action-child-list">{children.map((child, index) => <div key={child.id} className="okr-action-child-item"><span className="okr-action-child-index">A{index + 1}</span><Typography.Text>{child.payload.title}</Typography.Text><Typography.Text type="secondary">{child.payload.department}</Typography.Text><Typography.Text type="secondary">{child.payload.assigneeName || '未指定承接人员'}</Typography.Text><Typography.Text type="secondary">{child.payload.deadline}</Typography.Text>{child.status === 'draft' && <Button type="link" onClick={() => openEditor(parent, child.id)}>编辑草稿</Button>}<div className="okr-action-child-detail"><span>{childDetail(child)}</span><span>{child.payload.milestone || '—'}</span><span>权重 {child.payload.weight || 0}%</span></div></div>)}</div> : <Typography.Paragraph type="secondary" className="okr-action-empty-child">暂无子动作，点击右侧图标开始拆解</Typography.Paragraph>}</>}</Card>; })}</Flex>}
  </div></Card>;
}
