package com.shichuang.manage.product;
import com.shichuang.manage.auth.RequestContext;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.*;

@Service
public class ProductLineService {
 private final ProductLineMapper mapper;
 public ProductLineService(ProductLineMapper mapper){this.mapper=mapper;}
 public List<Map<String,Object>> list(String keyword){return mapper.list(RequestContext.tenantId(),keyword==null?"":keyword.trim()).stream().map(this::enrich).toList();}
 public Map<String,Object> detail(String id){Map<String,Object> line=mapper.find(RequestContext.tenantId(),id); if(line==null) throw new NoSuchElementException("产品线不存在"); line.put("requirements",mapper.requirements(RequestContext.tenantId(),id)); return enrich(line);}
 @Transactional public Map<String,Object> create(Map<String,Object>b){if(String.valueOf(b.getOrDefault("name","")).isBlank()) throw new IllegalArgumentException("产品线名称不能为空"); if(!b.containsKey("description") || String.valueOf(b.get("description")).isBlank()) b.put("description","该产品线还没有任何简介内容。"); String id=UUID.randomUUID().toString(); String code=String.valueOf(b.getOrDefault("code","PL-"+String.format("%03d",mapper.count(RequestContext.tenantId())+1))); mapper.insert(RequestContext.tenantId(),id,code,b,RequestContext.userId()); mapper.addActivity(RequestContext.tenantId(),id,"创建产品线",String.valueOf(b.get("name")),RequestContext.operatorName()); if(b.get("members") instanceof List<?> members) replaceMembers(id,members); return Map.of("id",id,"code",code);}
 @Transactional public void update(String id,Map<String,Object>b){Map<String,Object> before=mapper.find(RequestContext.tenantId(),id); if(before==null || mapper.update(RequestContext.tenantId(),id,b,RequestContext.userId())==0) throw new NoSuchElementException("产品线不存在"); recordChanges(id,b,before); if(b.get("members") instanceof List<?> members) replaceMembers(id,members);}
 @Transactional public void status(String id,String status){if(!Set.of("启用中","已停用").contains(status)) throw new IllegalArgumentException("状态无效"); if(mapper.status(RequestContext.tenantId(),id,status,RequestContext.userId())==0) throw new NoSuchElementException("产品线不存在"); mapper.addActivity(RequestContext.tenantId(),id,"修改产品线状态",status,RequestContext.operatorName());}
 public List<Map<String,Object>> members(String id){return mapper.members(RequestContext.tenantId(),id);} @Transactional public void addMember(String id,Map<String,Object>b){requireLine(id); String name=String.valueOf(b.getOrDefault("memberName",b.get("name"))).trim(); String role=String.valueOf(b.get("role")).trim(); if(name.isBlank()) throw new IllegalArgumentException("成员名称不能为空"); if(!Set.of("管理员","产品","研发","设计","测试","参与人").contains(role)) throw new IllegalArgumentException("成员角色无效"); mapper.addMember(RequestContext.tenantId(),id,Map.of("memberName",name,"role",role),RequestContext.userId()); mapper.addActivity(RequestContext.tenantId(),id,"添加成员角色",name+" · "+role,RequestContext.operatorName());}
 @Transactional public void removeMember(String id,String memberId){Map<String,Object> member=mapper.member(RequestContext.tenantId(),id,memberId); if(member==null || mapper.removeMember(RequestContext.tenantId(),id,memberId,RequestContext.userId())==0) throw new NoSuchElementException("成员不存在"); mapper.addActivity(RequestContext.tenantId(),id,"移除成员角色",member.get("name")+" · "+member.get("role"),RequestContext.operatorName());}
 public List<Map<String,Object>> versions(String id){return mapper.versions(RequestContext.tenantId(),id);} @Transactional public void addVersion(String id,Map<String,Object>b){Map<String,Object> line=mapper.find(RequestContext.tenantId(),id); if(line==null) throw new NoSuchElementException("产品线不存在"); if(String.valueOf(b.getOrDefault("ownerName","")).isBlank()) b.put("ownerName",line.get("ownerName")); mapper.addVersion(RequestContext.tenantId(),id,b,RequestContext.userId()); mapper.updateCurrentVersion(RequestContext.tenantId(),id,String.valueOf(b.get("code")),RequestContext.userId()); mapper.addActivity(RequestContext.tenantId(),id,"创建版本",String.valueOf(b.get("code")),RequestContext.operatorName());} @Transactional public void updateVersion(String lineId,String versionId,Map<String,Object>b){Map<String,Object> version=mapper.version(RequestContext.tenantId(),versionId); if(version==null || !lineId.equals(String.valueOf(version.get("productLineId"))) || mapper.updateVersion(RequestContext.tenantId(),versionId,b,RequestContext.userId())==0) throw new NoSuchElementException("版本不存在"); mapper.addActivity(RequestContext.tenantId(),lineId,"修改版本",String.valueOf(version.get("code")),RequestContext.operatorName());}
 @Transactional public void deleteVersion(String lineId,String versionId){Map<String,Object> version=mapper.version(RequestContext.tenantId(),versionId); if(version==null || !lineId.equals(String.valueOf(version.get("productLineId"))) || mapper.deleteVersion(RequestContext.tenantId(),lineId,versionId,RequestContext.userId())==0) throw new NoSuchElementException("版本不存在"); mapper.addActivity(RequestContext.tenantId(),lineId,"删除版本",String.valueOf(version.get("code")),RequestContext.operatorName());}
 public List<Map<String,Object>> activities(String id){return mapper.activities(RequestContext.tenantId(),id);}
 private Map<String,Object> enrich(Map<String,Object> line){String id=String.valueOf(line.get("id")); line.put("members",mapper.members(RequestContext.tenantId(),id)); line.put("versions",mapper.versions(RequestContext.tenantId(),id)); line.put("activities",mapper.activities(RequestContext.tenantId(),id)); return line;}
 private void recordChanges(String id,Map<String,Object> body,Map<String,Object> before){Map<String,String> labels=Map.of("name","修改产品线名称","ownerName","修改综合负责人","requirementOwner","修改需求负责人","techOwner","修改技术负责人","testOwner","修改测试负责人","status","修改产品线状态"); labels.forEach((field,action)->{if(!body.containsKey(field)) return; Object next=body.get(field); String previous=String.valueOf(before.getOrDefault(field,"")); String current=next==null?"":String.valueOf(next); if(!Objects.equals(previous,current)) mapper.addActivity(RequestContext.tenantId(),id,action,current.isBlank()?"未设置":current,RequestContext.operatorName());});}
 private void replaceMembers(String id,List<?> members){List<Map<String,Object>> previous=mapper.members(RequestContext.tenantId(),id); mapper.removeAllMembers(RequestContext.tenantId(),id,RequestContext.userId()); for(Object value:members){if(value instanceof Map<?,?> raw){Map<String,Object> member=new HashMap<>(); raw.forEach((key,val)->member.put(String.valueOf(key),val)); mapper.addMember(RequestContext.tenantId(),id,member,RequestContext.userId()); mapper.addActivity(RequestContext.tenantId(),id,"添加成员角色",String.valueOf(member.getOrDefault("memberName",member.get("name")))+" · "+String.valueOf(member.get("role")),RequestContext.operatorName());}} for(Map<String,Object> member:previous) mapper.addActivity(RequestContext.tenantId(),id,"移除成员角色",member.get("name")+" · "+member.get("role"),RequestContext.operatorName());}
 private void requireLine(String id){if(mapper.find(RequestContext.tenantId(),id)==null) throw new NoSuchElementException("产品线不存在");}
}
