package com.shichuang.manage.product;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.ArrayList;

@Repository
public class ProductLineMapper {
  private final JdbcTemplate jdbc;
  private final ObjectMapper objectMapper;
  public ProductLineMapper(JdbcTemplate jdbc, ObjectMapper objectMapper) { this.jdbc = jdbc; this.objectMapper = objectMapper; }
  List<Map<String,Object>> list(String tenant, String keyword, String userId, boolean admin) { String like = "%" + keyword + "%"; return jdbc.queryForList("SELECT id_ AS id,code_ AS code,name_ AS name,description_ AS description,visibility_ AS visibility,owner_name_ AS ownerName,requirement_owner_ AS requirementOwner,tech_owner_ AS techOwner,test_owner_ AS testOwner,website_ AS website,cover_image_ AS coverImage,status_ AS health,current_version_ AS currentVersion FROM t_product_line p WHERE tenant_id_=? AND delete_flag_=0 AND (name_ LIKE ? OR code_ LIKE ?) AND (?=1 OR COALESCE(NULLIF(visibility_,''),'公开')='公开' OR create_by_=? OR (visibility_='私密' AND EXISTS (SELECT 1 FROM t_product_line_member m WHERE m.tenant_id_=p.tenant_id_ AND m.product_line_id_=p.id_ AND m.user_id_=? AND m.delete_flag_=0))) ORDER BY create_time_ DESC", tenant, like, like, admin ? 1 : 0, userId, userId); }
  Map<String,Object> find(String tenant, String id) { List<Map<String,Object>> rows=jdbc.queryForList("SELECT id_ AS id,code_ AS code,name_ AS name,description_ AS description,visibility_ AS visibility,owner_name_ AS ownerName,requirement_owner_ AS requirementOwner,tech_owner_ AS techOwner,test_owner_ AS testOwner,website_ AS website,cover_image_ AS coverImage,status_ AS health,current_version_ AS currentVersion FROM t_product_line WHERE tenant_id_=? AND id_=? AND delete_flag_=0",tenant,id); return rows.isEmpty()?null:rows.get(0); }
  void insert(String tenant,String id,String code,Map<String,Object>b,String user){ jdbc.update("INSERT INTO t_product_line(id_,tenant_id_,code_,name_,description_,visibility_,owner_name_,requirement_owner_,tech_owner_,test_owner_,website_,cover_image_,status_,current_version_,create_by_,update_by_,create_time_,update_time_) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW(),NOW())",id,tenant,code,b.get("name"),b.get("description"),b.getOrDefault("visibility","公开"),b.get("ownerName"),b.get("requirementOwner"),b.get("techOwner"),b.get("testOwner"),b.get("website"),b.get("coverImage"),b.getOrDefault("status","启用中"),b.getOrDefault("currentVersion","1.0.0"),user,user); }
  int update(String tenant,String id,Map<String,Object>b,String user){ return jdbc.update("UPDATE t_product_line SET name_=COALESCE(?,name_),description_=COALESCE(?,description_),visibility_=COALESCE(?,visibility_),owner_name_=COALESCE(?,owner_name_),requirement_owner_=COALESCE(?,requirement_owner_),tech_owner_=COALESCE(?,tech_owner_),test_owner_=COALESCE(?,test_owner_),website_=COALESCE(?,website_),cover_image_=COALESCE(?,cover_image_),status_=COALESCE(?,status_),current_version_=COALESCE(?,current_version_),update_by_=?,version_=version_+1,update_time_=NOW() WHERE tenant_id_=? AND id_=? AND delete_flag_=0",b.get("name"),b.get("description"),b.get("visibility"),b.get("ownerName"),b.get("requirementOwner"),b.get("techOwner"),b.get("testOwner"),b.get("website"),b.get("coverImage"),b.get("status"),b.get("currentVersion"),user,tenant,id); }
  int status(String tenant,String id,String status,String user){ return jdbc.update("UPDATE t_product_line SET status_=?,update_by_=?,version_=version_+1,update_time_=NOW() WHERE tenant_id_=? AND id_=? AND delete_flag_=0",status,user,tenant,id); }
  long count(String tenant){ Long n=jdbc.queryForObject("SELECT COUNT(*) FROM t_product_line WHERE tenant_id_=? AND delete_flag_=0",Long.class,tenant); return n==null?0:n; }
  List<Map<String,Object>> members(String tenant,String id){ return jdbc.queryForList("SELECT id_ AS id,user_id_ AS userId,member_name_ AS name,role_ AS role FROM t_product_line_member WHERE tenant_id_=? AND product_line_id_=? AND delete_flag_=0 ORDER BY create_time_",tenant,id); }
  List<Map<String,Object>> membersForLines(String tenant,List<String> ids){ return ids.isEmpty()?List.of():jdbc.queryForList("SELECT product_line_id_ AS productLineId,id_ AS id,user_id_ AS userId,member_name_ AS name,role_ AS role FROM t_product_line_member WHERE tenant_id_=? AND product_line_id_ IN ("+placeholders(ids.size())+") AND delete_flag_=0 ORDER BY create_time_",batchArgs(tenant,ids)); }
  Map<String,Object> member(String tenant,String lineId,String memberId){ List<Map<String,Object>> rows=jdbc.queryForList("SELECT id_ AS id,member_name_ AS name,role_ AS role FROM t_product_line_member WHERE tenant_id_=? AND product_line_id_=? AND id_=? AND delete_flag_=0",tenant,lineId,memberId); return rows.isEmpty()?null:rows.get(0); }
  String userIdByName(String tenant,String name){ List<String> rows=jdbc.queryForList("SELECT id_ FROM t_sys_user WHERE tenant_id_=? AND name_=? AND status_='enabled' AND delete_flag_=0 ORDER BY create_time_ LIMIT 1",String.class,tenant,name); return rows.isEmpty()?null:rows.get(0); }
  boolean activeMemberExists(String tenant,String lineId,String userId,String name){ Long count=jdbc.queryForObject("SELECT COUNT(*) FROM t_product_line_member WHERE tenant_id_=? AND product_line_id_=? AND delete_flag_=0 AND ((?<>'' AND user_id_=?) OR ((user_id_ IS NULL OR user_id_='') AND member_name_=?))",Long.class,tenant,lineId,userId,userId,name); return count!=null&&count>0; }
  void addMember(String tenant,String lineId,Map<String,Object>b,String user){ jdbc.update("INSERT INTO t_product_line_member(id_,tenant_id_,product_line_id_,user_id_,member_name_,role_,create_by_,update_by_,create_time_,update_time_) VALUES(?,?,?,?,?,?,?,?,NOW(),NOW())",UUID.randomUUID().toString(),tenant,lineId,b.get("userId"),b.getOrDefault("memberName",b.get("name")),b.get("role"),user,user); }
  int removeMember(String tenant,String lineId,String memberId,String user){ return jdbc.update("UPDATE t_product_line_member SET delete_flag_=1,update_by_=?,update_time_=NOW() WHERE tenant_id_=? AND product_line_id_=? AND id_=? AND delete_flag_=0",user,tenant,lineId,memberId); }
  int updateMemberRole(String tenant,String lineId,String memberId,String role,String user){ return jdbc.update("UPDATE t_product_line_member SET role_=?,update_by_=?,update_time_=NOW() WHERE tenant_id_=? AND product_line_id_=? AND id_=? AND delete_flag_=0",role,user,tenant,lineId,memberId); }
  int removeAllMembers(String tenant,String lineId,String user){ return jdbc.update("UPDATE t_product_line_member SET delete_flag_=1,update_by_=?,update_time_=NOW() WHERE tenant_id_=? AND product_line_id_=? AND delete_flag_=0",user,tenant,lineId); }
  List<Map<String,Object>> workItemTypes(String tenant,String lineId,String category){ String sql="SELECT id_ AS id,category_ AS category,name_ AS name,description_ AS description,creator_name_ AS creatorName,create_time_ AS createdAt,enabled_ AS enabled FROM t_product_line_work_item_type WHERE tenant_id_=? AND product_line_id_=? AND delete_flag_=0"+(category==null?"":" AND category_=?")+" ORDER BY create_time_ DESC"; return category==null?jdbc.queryForList(sql,tenant,lineId):jdbc.queryForList(sql,tenant,lineId,category); }
  List<Map<String,Object>> workItemTypesForLines(String tenant,List<String> ids){ return ids.isEmpty()?List.of():jdbc.queryForList("SELECT product_line_id_ AS productLineId,id_ AS id,category_ AS category,name_ AS name,description_ AS description,creator_name_ AS creatorName,create_time_ AS createdAt,enabled_ AS enabled FROM t_product_line_work_item_type WHERE tenant_id_=? AND product_line_id_ IN ("+placeholders(ids.size())+") AND delete_flag_=0 ORDER BY create_time_ DESC",batchArgs(tenant,ids)); }
  Map<String,Object> workItemType(String tenant,String lineId,String typeId){ List<Map<String,Object>> rows=jdbc.queryForList("SELECT id_ AS id,category_ AS category,name_ AS name,description_ AS description,creator_name_ AS creatorName,create_time_ AS createdAt,enabled_ AS enabled FROM t_product_line_work_item_type WHERE tenant_id_=? AND product_line_id_=? AND id_=? AND delete_flag_=0",tenant,lineId,typeId); return rows.isEmpty()?null:rows.get(0); }
  void addWorkItemType(String tenant,String lineId,String typeId,Map<String,Object>b,String user,String creatorName){ jdbc.update("INSERT INTO t_product_line_work_item_type(id_,tenant_id_,product_line_id_,category_,name_,description_,creator_name_,create_by_,update_by_,create_time_,update_time_,enabled_) VALUES(?,?,?,?,?,?,?,?,?,NOW(),NOW(),?)",typeId,tenant,lineId,b.get("category"),b.get("name"),b.getOrDefault("description",""),creatorName,user,user,Boolean.TRUE.equals(b.get("enabled"))?1:0); }
  int updateWorkItemType(String tenant,String lineId,String typeId,Map<String,Object>b,String user){ return jdbc.update("UPDATE t_product_line_work_item_type SET category_=COALESCE(?,category_),name_=COALESCE(?,name_),description_=COALESCE(?,description_),enabled_=COALESCE(?,enabled_),update_by_=?,update_time_=NOW(),version_=version_+1 WHERE tenant_id_=? AND product_line_id_=? AND id_=? AND delete_flag_=0",b.get("category"),b.get("name"),b.get("description"),b.containsKey("enabled")?(Boolean.TRUE.equals(b.get("enabled"))?1:0):null,user,tenant,lineId,typeId); }
  int deleteWorkItemType(String tenant,String lineId,String typeId,String user){ return jdbc.update("UPDATE t_product_line_work_item_type SET delete_flag_=1,update_by_=?,update_time_=NOW() WHERE tenant_id_=? AND product_line_id_=? AND id_=? AND delete_flag_=0",user,tenant,lineId,typeId); }
  boolean workItemTypeReferenced(String tenant,String typeId){
    Long count=jdbc.queryForObject("SELECT (SELECT COUNT(*) FROM t_product_work_item WHERE tenant_id_=? AND task_type_id_=?)+(SELECT COUNT(*) FROM t_product_work_item_child_rule WHERE tenant_id_=? AND (parent_type_id_=? OR child_type_id_=?))",Long.class,tenant,typeId,tenant,typeId,typeId);
    return count!=null && count>0;
  }
  List<Map<String,Object>> versions(String tenant,String id){ return jdbc.queryForList("SELECT id_ AS id,code_ AS code,name_ AS name,owner_name_ AS ownerName,product_line_id_ AS productLineId,start_date_ AS startDate,end_date_ AS endDate,content_ AS content,status_ AS status,linked_requirement_ids_ AS linkedRequirementIds,create_time_ AS createdAt FROM t_product_line_version WHERE tenant_id_=? AND product_line_id_=? AND delete_flag_=0 ORDER BY start_date_ DESC,create_time_ DESC",tenant,id); }
  List<Map<String,Object>> versionsForLines(String tenant,List<String> ids){ return ids.isEmpty()?List.of():jdbc.queryForList("SELECT id_ AS id,code_ AS code,name_ AS name,owner_name_ AS ownerName,product_line_id_ AS productLineId,start_date_ AS startDate,end_date_ AS endDate,content_ AS content,status_ AS status,linked_requirement_ids_ AS linkedRequirementIds,create_time_ AS createdAt FROM t_product_line_version WHERE tenant_id_=? AND product_line_id_ IN ("+placeholders(ids.size())+") AND delete_flag_=0 ORDER BY start_date_ DESC,create_time_ DESC",batchArgs(tenant,ids)); }
  Map<String,Object> version(String tenant,String id){ List<Map<String,Object>> rows=jdbc.queryForList("SELECT id_ AS id,code_ AS code,name_ AS name,product_line_id_ AS productLineId,start_date_ AS startDate,end_date_ AS endDate FROM t_product_line_version WHERE tenant_id_=? AND id_=? AND delete_flag_=0",tenant,id); return rows.isEmpty()?null:rows.get(0); }
  List<Map<String,Object>> requirements(String tenant,String id){ return jdbc.queryForList("SELECT w.id_ AS id,w.code_ AS code,w.title_ AS title,w.status_name_ AS status,w.priority_ AS priority,w.assignee_name_ AS ownerName,COALESCE(v.name_,'') AS versionName FROM t_product_work_item w LEFT JOIN t_product_line_version v ON v.id_=w.version_id_ AND v.tenant_id_=w.tenant_id_ AND v.delete_flag_=0 WHERE w.tenant_id_=? AND w.product_line_id_=? AND w.category_='requirement' AND w.delete_flag_=0 ORDER BY w.create_time_ DESC",tenant,id); }
  void addVersion(String tenant,String lineId,Map<String,Object>b,String user){ jdbc.update("INSERT INTO t_product_line_version(id_,tenant_id_,product_line_id_,code_,name_,owner_name_,start_date_,end_date_,content_,status_,linked_requirement_ids_,create_by_,update_by_,create_time_,update_time_) VALUES(?,?,?,?,?,?,?,?,?, ?,CAST(? AS JSON),?,?,NOW(),NOW())",UUID.randomUUID().toString(),tenant,lineId,b.get("code"),b.get("name"),b.get("ownerName"),b.get("startDate"),b.get("endDate"),b.get("content"),b.getOrDefault("status","待开始"),json(b.getOrDefault("linkedRequirementIds",List.of())),user,user); }
  int updateCurrentVersion(String tenant,String lineId,String code,String user){ return jdbc.update("UPDATE t_product_line SET current_version_=?,update_by_=?,version_=version_+1,update_time_=NOW() WHERE tenant_id_=? AND id_=? AND delete_flag_=0",code,user,tenant,lineId); }
  int updateVersion(String tenant,String id,Map<String,Object>b,String user){ return jdbc.update("UPDATE t_product_line_version SET name_=COALESCE(?,name_),owner_name_=COALESCE(?,owner_name_),start_date_=CASE WHEN ? THEN ? ELSE start_date_ END,end_date_=CASE WHEN ? THEN ? ELSE end_date_ END,content_=COALESCE(?,content_),status_=COALESCE(?,status_),linked_requirement_ids_=COALESCE(CAST(? AS JSON),linked_requirement_ids_),update_by_=?,version_=version_+1,update_time_=NOW() WHERE tenant_id_=? AND id_=? AND delete_flag_=0",b.get("name"),b.get("ownerName"),b.containsKey("startDate"),b.get("startDate"),b.containsKey("endDate"),b.get("endDate"),b.get("content"),b.get("status"),json(b.get("linkedRequirementIds")),user,tenant,id); }
  int deleteVersion(String tenant,String lineId,String versionId,String user){ return jdbc.update("UPDATE t_product_line_version SET delete_flag_=1,update_by_=?,update_time_=NOW() WHERE tenant_id_=? AND product_line_id_=? AND id_=? AND delete_flag_=0",user,tenant,lineId,versionId); }
  Map<String,Object> workItem(String tenant,String kind,String itemId){ List<Map<String,Object>> rows=jdbc.queryForList("SELECT id_ AS id,product_line_id_ AS productLineId FROM t_product_work_item WHERE tenant_id_=? AND id_=? AND category_=? AND delete_flag_=0",tenant,itemId,kind); return rows.isEmpty()?null:rows.get(0); }
  int assignWorkItem(String tenant,String kind,String itemId,String versionId,String versionName,String user){ return jdbc.update("UPDATE t_product_work_item SET version_id_=?,update_by_=?,update_time_=NOW(6),version_=version_+1 WHERE tenant_id_=? AND id_=? AND category_=? AND delete_flag_=0",versionId,user,tenant,itemId,kind); }
  int unassignWorkItem(String tenant,String kind,String itemId,String user){ return jdbc.update("UPDATE t_product_work_item SET version_id_=NULL,update_by_=?,update_time_=NOW(6),version_=version_+1 WHERE tenant_id_=? AND id_=? AND category_=? AND delete_flag_=0",user,tenant,itemId,kind); }
  List<Map<String,Object>> activities(String tenant,String lineId){ return jdbc.queryForList("SELECT id_ AS id,action_ AS action,detail_ AS detail,operator_name_ AS operatorName,create_time_ AS createdAt FROM t_product_line_activity WHERE tenant_id_=? AND product_line_id_=? ORDER BY create_time_ DESC",tenant,lineId); }
  List<Map<String,Object>> activitiesForLines(String tenant,List<String> ids){ return ids.isEmpty()?List.of():jdbc.queryForList("SELECT product_line_id_ AS productLineId,id_ AS id,action_ AS action,detail_ AS detail,operator_name_ AS operatorName,create_time_ AS createdAt FROM t_product_line_activity WHERE tenant_id_=? AND product_line_id_ IN ("+placeholders(ids.size())+") ORDER BY create_time_ DESC",batchArgs(tenant,ids)); }
  void addActivity(String tenant,String lineId,String action,String detail,String operatorName){ jdbc.update("INSERT INTO t_product_line_activity(id_,tenant_id_,product_line_id_,action_,detail_,operator_name_,create_time_) VALUES(?,?,?,?,?,?,NOW())",UUID.randomUUID().toString(),tenant,lineId,action,detail,operatorName); }
  private String json(Object value) { try { return objectMapper.writeValueAsString(value); } catch (JsonProcessingException e) { throw new IllegalArgumentException("版本关联需求格式无效", e); } }
  private String placeholders(int size){ return String.join(",",java.util.Collections.nCopies(size,"?")); }
  private Object[] batchArgs(String tenant,List<String> ids){ List<Object> args=new ArrayList<>(); args.add(tenant); args.addAll(ids); return args.toArray(); }
}
