import { useState } from 'react';
import { App, Button, Checkbox, Drawer, Form, Input, InputNumber, Modal, Popconfirm, Radio, Select, Space, Switch, Table, Tabs, Tag } from 'antd';
import { PlusOutlined, ReloadOutlined, SearchOutlined } from '@ant-design/icons';
import { batchWindow, submitTrainingExam, type TrainingBatch, type TrainingPaper, type TrainingState } from '../../services/trainingRepository';
import { TrainingBatchLearners, TrainingBatchResults, TrainingPaperQuestions } from './TrainingExamDetails';
import { dateLabel, pagination, type TrainingPerson } from './TrainingRecords';

type Props = { state: TrainingState; person: TrainingPerson; commit: (state: TrainingState) => boolean; management?: boolean };
const totalScore = (paper?: TrainingPaper) => paper?.questions.reduce((sum, question) => sum + question.points, 0) || 0;
const optionLabel = (index: number) => String.fromCharCode(65 + index);
export function TrainingExams({ state, person, commit, management = false }: Props) {
  const { message, modal } = App.useApp();
  const [tab, setTab] = useState('papers'); const [query, setQuery] = useState(''); const [status, setStatus] = useState('all'); const [applied, setApplied] = useState({ query: '', status: 'all' });
  const [editingPaper, setEditingPaper] = useState<TrainingPaper>(); const [editingBatch, setEditingBatch] = useState<TrainingBatch>(); const [questionsPaper, setQuestionsPaper] = useState<TrainingPaper>();
  const [inspecting, setInspecting] = useState<{ batch: TrainingBatch; mode: 'learners' | 'results' }>();
  const [taking, setTaking] = useState<TrainingBatch>(); const [answers, setAnswers] = useState<Record<string, number | number[] | string>>({});
  const [paperForm] = Form.useForm(); const [batchForm] = Form.useForm();
  const reset = () => { setQuery(''); setStatus('all'); setApplied({ query: '', status: 'all' }); };
  const paperFor = (batch: TrainingBatch) => state.papers.find(paper => paper.id === batch.paperId);
  const attemptFor = (batch: TrainingBatch) => state.attempts.find(attempt => attempt.batchId === batch.id && attempt.userId === person.id);
  const locked = (paper: TrainingPaper) => state.batches.some(batch => batch.paperId === paper.id);
  const openPaper = (paper?: TrainingPaper) => { const value = paper || { id: crypto.randomUUID(), name: '', passScore: 60, enabled: true, questions: [] }; paperForm.setFieldsValue(value); setEditingPaper(value); };
  const openBatch = (batch?: TrainingBatch) => { const value = batch || { id: crypto.randomUUID(), name: '', paperId: undefined, start: '', end: '', enabled: true, learnerIds: [] }; batchForm.setFieldsValue(value); setEditingBatch(value as TrainingBatch); };
  const tableSearch = <div className="training-toolbar"><Input allowClear placeholder={tab === 'papers' ? '搜索试卷名称' : '搜索批次 / 试卷'} value={query} onChange={event => setQuery(event.target.value)} onPressEnter={() => setApplied({ query, status })} style={{ width: 280 }} /><Select aria-label="考核状态" value={status} onChange={setStatus} style={{ width: 160 }} options={[{ value: 'all', label: '全部状态' }, { value: 'enabled', label: '启用' }, { value: 'disabled', label: '停用' }]} /><Button type="primary" icon={<SearchOutlined />} onClick={() => setApplied({ query, status })}>查询</Button><Button icon={<ReloadOutlined />} onClick={reset}>重置</Button></div>;
  const enabledFilter = (enabled: boolean) => applied.status === 'all' || enabled === (applied.status === 'enabled');
  const activePaper = taking && paperFor(taking);
  return <section className="training-list-section">
    {management ? <><Tabs activeKey={tab} onChange={value => { setTab(value); reset(); }} items={[{ key: 'papers', label: '试卷管理' }, { key: 'batches', label: '考核批次' }]} /><div className="training-toolbar-row">{tableSearch}<Button type="primary" icon={<PlusOutlined />} onClick={() => tab === 'papers' ? openPaper() : openBatch()}>{tab === 'papers' ? '新建试卷' : '新建批次'}</Button></div>
      {tab === 'papers' ? <Table rowKey="id" pagination={pagination} scroll={{ x: 960 }} dataSource={state.papers.filter(paper => paper.name.includes(applied.query.trim()) && enabledFilter(paper.enabled))} columns={[
        { title: '试卷名称', dataIndex: 'name', ellipsis: true }, { title: '题量', width: 80, render: (_, paper) => paper.questions.length }, { title: '总分', width: 80, render: (_, paper) => totalScore(paper) }, { title: '及格分', dataIndex: 'passScore', width: 100 }, { title: '状态', width: 90, render: (_, paper) => <Tag color={paper.enabled ? 'success' : 'default'}>{paper.enabled ? '启用' : '停用'}</Tag> },
        { title: '操作', width: 320, render: (_, paper) => <Space size={0}><Button type="link" onClick={() => openPaper(paper)}>编辑</Button><Button type="link" onClick={() => setQuestionsPaper(paper)}>题目配置</Button><Button type="link" onClick={() => commit({ ...state, papers: state.papers.map(item => item.id === paper.id ? { ...item, enabled: !item.enabled } : item) })}>{paper.enabled ? '停用' : '启用'}</Button><Popconfirm title="删除这份试卷？" description="删除后关联批次和成绩记录也会一并移除，是否继续？" onConfirm={() => commit({ ...state, papers: state.papers.filter(item => item.id !== paper.id), batches: state.batches.filter(batch => batch.paperId !== paper.id), attempts: state.attempts.filter(attempt => !state.batches.some(batch => batch.paperId === paper.id && batch.id === attempt.batchId)) })}><Button type="link" danger>删除</Button></Popconfirm></Space> }
      ]} /> : <Table rowKey="id" pagination={pagination} scroll={{ x: 1160 }} dataSource={state.batches.filter(batch => `${batch.name}${paperFor(batch)?.name || ''}`.includes(applied.query.trim()) && enabledFilter(batch.enabled))} columns={[
        { title: '批次名称', dataIndex: 'name', width: 200, ellipsis: true }, { title: '试卷', width: 180, ellipsis: true, render: (_, batch) => paperFor(batch)?.name || '试卷已移除' }, { title: '时间窗', width: 250, render: (_, batch) => `${dateLabel(batch.start)} ~ ${dateLabel(batch.end)}` }, { title: '窗口', width: 100, render: (_, batch) => <Tag color={batchWindow(batch) === '进行中' ? 'success' : 'default'}>{batchWindow(batch)}</Tag> }, { title: '学员', width: 70, render: (_, batch) => batch.learnerIds.length }, { title: '已交', width: 70, render: (_, batch) => state.attempts.filter(attempt => attempt.batchId === batch.id).length }, { title: '状态', width: 90, render: (_, batch) => <Tag color={batch.enabled ? 'success' : 'default'}>{batch.enabled ? '启用' : '停用'}</Tag> },
        { title: '操作', width: 300, fixed: 'right', render: (_, batch) => <Space size={0}><Button type="link" onClick={() => openBatch(batch)}>编辑</Button><Button type="link" onClick={() => setInspecting({ batch, mode: 'learners' })}>学员</Button><Button type="link" onClick={() => setInspecting({ batch, mode: 'results' })}>考核情况</Button><Popconfirm title="删除这个考核批次？" description="删除后该批次的成绩记录也会一并移除，是否继续？" onConfirm={() => commit({ ...state, batches: state.batches.filter(item => item.id !== batch.id), attempts: state.attempts.filter(attempt => attempt.batchId !== batch.id) })}><Button type="link" danger>删除</Button></Popconfirm></Space> }
      ]} />}</> : <><Table rowKey="id" dataSource={state.batches.filter(batch => batch.learnerIds.includes(person.id))} pagination={pagination} scroll={{ x: 1000 }} columns={[
        { title: '考核批次', dataIndex: 'name', width: 240 }, { title: '试卷', width: 200, render: (_, batch) => paperFor(batch)?.name || '试卷已移除' }, { title: '时间', width: 280, render: (_, batch) => `${dateLabel(batch.start)} ~ ${dateLabel(batch.end)}` }, { title: '状态', width: 100, render: (_, batch) => <Tag color={attemptFor(batch) ? 'success' : 'default'}>{attemptFor(batch) ? '已交卷' : batchWindow(batch)}</Tag> }, { title: '得分', width: 90, render: (_, batch) => attemptFor(batch)?.score ?? '—' },
        { title: '操作', width: 130, render: (_, batch) => attemptFor(batch) ? <Button type="link" onClick={() => modal.info({ title: '演示考核结果', content: `得分 ${attemptFor(batch)!.score} / ${totalScore(paperFor(batch))}，及格分 ${paperFor(batch)?.passScore}。${attemptFor(batch)!.score >= (paperFor(batch)?.passScore || 0) ? '演示通过' : '演示未通过'}，不计入正式考核。` })}>查看结果</Button> : <Button type="link" disabled={batchWindow(batch) !== '进行中' || !paperFor(batch)?.enabled || !paperFor(batch)?.questions.length} onClick={() => { setAnswers({}); setTaking(batch); }}>开始演示考核</Button> }
      ]} /></>}
    <Modal title={state.papers.some(paper => paper.id === editingPaper?.id) ? '编辑试卷' : '新建试卷'} open={Boolean(editingPaper)} okText="保存" cancelText="取消" onCancel={() => setEditingPaper(undefined)} onOk={() => paperForm.validateFields().then(values => { if (!editingPaper) return; if (editingPaper.questions.length && values.passScore > totalScore(editingPaper)) { message.error('及格分不能超过总分'); return; } const paper = { ...editingPaper, ...values, name: values.name.trim() }; if (commit({ ...state, papers: [...state.papers.filter(item => item.id !== paper.id), paper] })) setEditingPaper(undefined); }).catch(() => undefined)}><Form name="training-paper" form={paperForm} layout="vertical"><Form.Item name="name" label="试卷名称" rules={[{ required: true, whitespace: true }]}><Input maxLength={80} /></Form.Item><Form.Item name="passScore" label="及格分" rules={[{ required: true }]}><InputNumber min={1} max={10000} precision={0} /></Form.Item><Form.Item name="enabled" label="启用" valuePropName="checked"><Switch /></Form.Item></Form></Modal>
    {questionsPaper && <TrainingPaperQuestions state={state} commit={commit} paper={questionsPaper} onClose={() => setQuestionsPaper(undefined)} />}
    <Modal title={state.batches.some(batch => batch.id === editingBatch?.id) ? '编辑批次' : '新建批次'} open={Boolean(editingBatch)} okText="保存" cancelText="取消" onCancel={() => setEditingBatch(undefined)} onOk={() => batchForm.validateFields().then(values => { if (!editingBatch) return; if (values.start && values.end && new Date(values.end) <= new Date(values.start)) { message.error('结束时间必须晚于开始时间'); return; } const paper = state.papers.find(item => item.id === values.paperId); if (!paper?.enabled || !paper.questions.length) { message.error('请选择已启用且已配置题目的试卷'); return; } const batch = { ...editingBatch, ...values, name: values.name.trim() }; if (commit({ ...state, batches: [...state.batches.filter(item => item.id !== batch.id), batch] })) setEditingBatch(undefined); }).catch(() => undefined)}><Form name="training-batch" form={batchForm} layout="vertical"><Form.Item label="批次名称" name="name" rules={[{ required: true, whitespace: true }]}><Input maxLength={80} /></Form.Item><Form.Item label="试卷" name="paperId" rules={[{ required: true }]}><Select options={state.papers.filter(paper => paper.enabled && paper.questions.length).map(paper => ({ value: paper.id, label: paper.name }))} /></Form.Item><Form.Item label="开始时间（可留空）" name="start"><Input type="datetime-local" /></Form.Item><Form.Item label="结束时间（可留空）" name="end"><Input type="datetime-local" /></Form.Item><Form.Item label="启用" name="enabled" valuePropName="checked"><Switch /></Form.Item></Form></Modal>
    {inspecting?.mode === 'learners' && <TrainingBatchLearners state={state} commit={commit} batch={inspecting.batch} person={person} onClose={() => setInspecting(undefined)} />}
    {inspecting?.mode === 'results' && <TrainingBatchResults state={state} batch={inspecting.batch} person={person} onClose={() => setInspecting(undefined)} />}
    <Drawer title={`演示考核 · ${taking?.name || ''}`} open={Boolean(taking)} width={720} onClose={() => setTaking(undefined)}>{activePaper?.questions.map((question, index) => <section key={question.id} className="training-question"><h3>{index + 1}. {question.title}（{question.type === 'multiple' ? '多选' : question.type === 'short' ? '简答' : '单选'} · {question.points}分）</h3>{question.type === 'short' ? <Input.TextArea value={typeof answers[question.id] === 'string' ? answers[question.id] as string : ''} rows={6} onChange={event => setAnswers({ ...answers, [question.id]: event.target.value })} placeholder="请输入简答内容" /> : question.type === 'multiple' ? <Checkbox.Group value={Array.isArray(answers[question.id]) ? answers[question.id] as number[] : []} onChange={value => setAnswers({ ...answers, [question.id]: value as number[] })}><Space orientation="vertical">{question.options.map((option, optionIndex) => <Checkbox key={optionIndex} value={optionIndex}>{optionLabel(optionIndex)}. {option}</Checkbox>)}</Space></Checkbox.Group> : <Radio.Group value={answers[question.id]} onChange={event => setAnswers({ ...answers, [question.id]: event.target.value })}><Space orientation="vertical">{question.options.map((option, optionIndex) => <Radio key={optionIndex} value={optionIndex}>{optionLabel(optionIndex)}. {option}</Radio>)}</Space></Radio.Group>}</section>)}<Popconfirm title="提交本次演示考核？" onConfirm={() => { if (!taking) return; try { if (commit(submitTrainingExam(state, taking.id, person.id, answers))) { setTaking(undefined); message.success('演示交卷已保存'); } } catch (cause) { message.error(cause instanceof Error ? cause.message : '交卷失败'); } }}><Button type="primary">提交演示考核</Button></Popconfirm></Drawer>
  </section>;
}
