<script setup lang="ts">
import {onMounted, reactive, ref, watch} from 'vue';
import {requirementRepository} from '../../services/requirementRepository';
import {productRepository} from '../../services/productRepository';
import RemoteSelect from './RemoteSelect.vue';
import VersionSelect from './VersionSelect.vue';
const props=defineProps<{kind:'requirement'|'design'|'dev'|'bug';modelValue?:Record<string,unknown>|null}>();
const emit=defineEmits<{save:[value:Record<string,unknown>];cancel:[]}>();
const form=reactive<any>({title:'',description:'',status:'',priority:'',ownerName:'',dueDate:'',productLineId:'',productLineName:'',versionId:'',iterationId:'',iterationName:'',parentId:''});
const employees=ref<Array<{value:string;label:string}>>([]); const productLines=ref<Array<{value:string;label:string}>>([]); const loadingOptions=ref(true); const syncing=ref(false);
watch(()=>props.modelValue,value=>{syncing.value=true;Object.assign(form,{title:'',description:'',status:'',priority:'',ownerName:'',dueDate:'',productLineId:'',productLineName:'',versionId:'',iterationId:'',iterationName:'',parentId:'',...(value||{})});syncing.value=false;},{immediate:true});
watch(()=>form.productLineId,(next,previous)=>{if(!syncing.value&&next!==previous)form.versionId='';});
onMounted(async()=>{try{const [people,lines]=await Promise.all([requirementRepository.employees(),productRepository.productLines()]);employees.value=people.map(item=>({value:String(item.name||item.id||''),label:String(item.name||item.id||'')})).filter(item=>item.value);productLines.value=lines.map(item=>({value:String(item.id||''),label:String(item.name||item.code||item.id||'')})).filter(item=>item.value);}finally{loadingOptions.value=false;}});
</script>
<template><a-form class="work-item-form" layout="vertical" @finish="emit('save',{...form,type:props.kind==='dev'?'development':props.kind})"><a-form-item label="标题" required><a-input v-model:value="form.title" placeholder="请输入标题"/></a-form-item><a-form-item label="描述"><a-textarea v-model:value="form.description" :rows="4" placeholder="请输入描述"/></a-form-item><div class="form-grid"><RemoteSelect v-model="form.status as string" label="状态" :options="[{value:'待排期',label:'待排期'},{value:'处理中',label:'处理中'},{value:'阻塞',label:'阻塞'},{value:'部分完成',label:'部分完成'},{value:'已完成',label:'已完成'}]" placeholder="请选择状态"/><RemoteSelect v-model="form.priority as string" label="优先级" :options="[{value:'紧急',label:'紧急'},{value:'高',label:'高'},{value:'中',label:'中'},{value:'低',label:'低'}]" placeholder="请选择优先级"/></div><RemoteSelect v-model="form.ownerName as string" label="负责人" :options="employees" :loading="loadingOptions" placeholder="请选择负责人"/><RemoteSelect v-model="form.productLineId as string" label="产品线" :options="productLines" :loading="loadingOptions" placeholder="请选择产品线"/><VersionSelect v-model="form.versionId as string" :product-line-id="String(form.productLineId||'')"/><a-form-item label="截止时间"><a-input v-model:value="form.dueDate" type="date"/></a-form-item><div class="form-actions"><a-button @click="emit('cancel')">取消</a-button><a-button type="primary" html-type="submit">保存</a-button></div></a-form></template>
