import React, { useEffect, useMemo, useState } from 'react';
import { Button, Empty, Input, Modal, Select, Switch, Tag, message } from 'antd';
import AntCard from 'antd/es/card/Card';
import { DeleteOutlined, EditOutlined, PlusOutlined, SettingOutlined } from '@ant-design/icons';
import { ProductLineWorkItemCategory } from '../../types';
import { productRepository, WorkItemCategoryKey, WorkItemTemplateType } from '../../services/productRepository';
import { WorkItemCategoryIcon } from '../product/WorkItemCategoryIcon';
import { CATEGORY_KEYS, buildWorkflowDefinition, createDefaultWorkItemStates, EditableWorkflowState, validateWorkflowStates, WorkItemStateEditor } from '../product/WorkItemStateConfigDrawer';

const CATEGORIES: ProductLineWorkItemCategory[] = ['需求', '设计', '研发', '测试', '缺陷', '用例'];
const categoryKey = (category: ProductLineWorkItemCategory) => CATEGORY_KEYS[category];
const normalizeStates = (item: WorkItemTemplateType | null): EditableWorkflowState[] => {
  const states = item?.workflow?.definition?.states;
  if (!states?.length) return createDefaultWorkItemStates(categoryKey(item?.category || '需求'));
  const initial = states.some((state) => state.initial);
  return states.map((state, index) => ({ ...state, key: String(state.key), name: String(state.name || ''), group: state.group as EditableWorkflowState['group'], initial: initial ? Boolean(state.initial) : index === 0, successful: state.group === 'COMPLETED', enabled: state.enabled !== false, stage: String(state.stage || categoryKey(item?.category || '需求')), color: state.color as EditableWorkflowState['color'] }));
};

export const WorkItemModuleView: React.FC = () => {
  const [items, setItems] = useState<WorkItemTemplateType[]>([]); const [category, setCategory] = useState<ProductLineWorkItemCategory | '全部'>('全部');
  const [editing, setEditing] = useState<WorkItemTemplateType | null>(null); const [open, setOpen] = useState(false); const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [enabled, setEnabled] = useState(true); const [isDefault, setIsDefault] = useState(false); const [states, setStates] = useState<EditableWorkflowState[]>(createDefaultWorkItemStates('requirement')); const [loading, setLoading] = useState(false);
  const visible = useMemo(() => category === '全部' ? items : items.filter((item) => item.category === category), [items, category]);
  const load = async () => { setLoading(true); try { setItems(await productRepository.workItemTemplate()); } catch (error) { message.error(error instanceof Error ? error.message : '工作项模版读取失败'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const openCreate = () => { setEditing(null); setName(''); setDescription(''); setEnabled(true); setIsDefault(false); setStates(createDefaultWorkItemStates(categoryKey(category === '全部' ? '需求' : category))); setOpen(true); };
  const openEdit = (item: WorkItemTemplateType) => { setEditing(item); setName(item.name); setDescription(item.description || ''); setEnabled(item.enabled !== false); setIsDefault(Boolean(item.isDefault)); setStates(normalizeStates(item)); setOpen(true); };
  const save = async () => {
    if (!name.trim()) { message.warning('请输入子类型名称'); return; } const invalid = validateWorkflowStates(states); if (invalid) { message.warning(invalid); return; }
    const typeCategory = editing?.category || (category === '全部' ? '需求' : category); const apiCategory = categoryKey(typeCategory); const definition = buildWorkflowDefinition(states.map((state) => ({ ...state, name: state.name.trim(), stage: apiCategory }))); setLoading(true);
    try { if (editing) { await productRepository.updateWorkItemTemplateType(editing.id, { name: name.trim(), description, enabled, isDefault }); await productRepository.updateWorkItemTemplateWorkflow(editing.id, { category: apiCategory, name: `${name.trim()}状态配置`, definition, revision: editing.workflow?.revision }); } else await productRepository.createWorkItemTemplateType({ category: typeCategory, name: name.trim(), description, enabled, isDefault, workflow: { category: apiCategory, name: `${name.trim()}状态配置`, definition } }); message.success(editing ? '模版已保存' : '子类型已创建'); setOpen(false); await load(); }
    catch (error) { message.error(error instanceof Error ? error.message : '保存失败'); } finally { setLoading(false); }
  };
  const remove = (item: WorkItemTemplateType) => Modal.confirm({ title: `删除「${item.name}」？`, content: '删除后新建产品不会再继承该子类型，已有产品不受影响。', okButtonProps: { danger: true }, onOk: async () => { await productRepository.deleteWorkItemTemplateType(item.id); message.success('子类型已删除'); await load(); } });
  return <div className="space-y-5 text-xs"><div className="flex items-start justify-between gap-4 border-b border-[var(--border-main)] pb-4"><div><h1 className="text-lg font-bold text-[var(--text-primary)]">工作项模版</h1><p className="mt-1 text-[var(--text-muted)]">配置新建产品默认继承的工作项子类型和状态流程。</p></div><Button type="primary" icon={<PlusOutlined />} onClick={openCreate}>新增子类型</Button></div>
    <AntCard className="border-[var(--border-main)] bg-[var(--bg-surface)]" loading={loading} title={<div className="flex items-center gap-2"><SettingOutlined />模版配置</div>} extra={<Select value={category} onChange={setCategory} options={[{ value: '全部', label: '全部分类' }, ...CATEGORIES.map((value) => ({ value, label: value }))]} style={{ width: 140 }} />}>
      {visible.length === 0 ? <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="暂无工作项模版" /> : <div className="overflow-x-auto"><div className="grid min-w-[900px] grid-cols-[150px_220px_minmax(360px,1fr)_110px_100px] border-b border-[var(--border-main)] bg-[var(--bg-surface-soft)] px-4 py-3 text-[11px] text-[var(--text-muted)]"><span>模块分类</span><span>子类型</span><span>状态流程</span><span>启用</span><span>操作</span></div>{visible.map((item) => <div key={item.id} className="grid min-w-[900px] grid-cols-[150px_220px_minmax(360px,1fr)_110px_100px] items-center gap-3 border-b border-[var(--border-main)] px-4 py-3"><div className="flex items-center gap-2 font-medium text-[var(--text-primary)]"><WorkItemCategoryIcon category={item.category === '用例' ? 'test' : categoryKey(item.category)} /><span>{item.category}</span></div><div className="text-[var(--text-body)]">{item.name}{item.isDefault && <Tag className="ml-2" color="blue">默认</Tag>}</div><div className="flex flex-wrap gap-2">{(item.workflow?.definition?.states || []).map((state) => <Tag key={state.key} color={state.group === 'COMPLETED' ? 'success' : state.initial ? 'default' : 'processing'}>{state.name}{state.initial ? ' · 初始' : ''}</Tag>)}</div><Switch size="small" checked={item.enabled !== false} onChange={async (checked) => { await productRepository.updateWorkItemTemplateType(item.id, { enabled: checked }); await load(); }} /><div className="flex gap-1"><Button type="text" icon={<EditOutlined />} aria-label={`编辑${item.name}`} onClick={() => openEdit(item)} /><Button type="text" danger icon={<DeleteOutlined />} aria-label={`删除${item.name}`} onClick={() => remove(item)} /></div></div>)}</div>}
    </AntCard>
    <Modal title={editing ? `编辑「${editing.name}」` : '新增工作项子类型'} open={open} width={900} destroyOnClose confirmLoading={loading} onCancel={() => setOpen(false)} onOk={() => void save()} okText="保存"><div className="space-y-4"><div className="grid grid-cols-2 gap-3"><label className="space-y-1"><span>分类</span><Select className="w-full" disabled={Boolean(editing)} value={editing?.category || (category === '全部' ? '需求' : category)} options={CATEGORIES.map((value) => ({ value, label: value }))} /></label><label className="space-y-1"><span>子类型名称</span><Input maxLength={128} value={name} onChange={(event) => setName(event.target.value)} /></label></div><label className="block space-y-1"><span>描述</span><Input.TextArea rows={2} value={description} onChange={(event) => setDescription(event.target.value)} /></label><div className="flex items-center justify-between"><span>启用并允许新建工作项</span><Switch checked={enabled} onChange={setEnabled} /></div><div className="flex items-center justify-between"><span>设为该分类默认子类型</span><Switch checked={isDefault} onChange={setIsDefault} /></div><div className="border-t border-[var(--border-main)] pt-4"><div className="mb-3 font-medium">状态流程</div><WorkItemStateEditor states={states} category={categoryKey(editing?.category || (category === '全部' ? '需求' : category)) as WorkItemCategoryKey} onChange={setStates} /></div></div></Modal>
  </div>;
};
